kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: amq-auth-keycloak
  labels:
    app: amq-auth-keycloak
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'amq-auth-keycloak:latest'
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-11-el7'
  source:
    type: Git
    git:
      uri: 'https://github.com/ippul/amq-auth-keycloak.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: amq-auth-keycloak-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: amq-auth-keycloak-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
