apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: {{ .Release.Namespace }}-user
spec:
  user:
    username: "ippul"
    firstName: "myFirstname"
    lastName: "myLastname"
    email: "ippul@arandommail.com"
    enabled: True
    emailVerified: False
    realmRoles:
      - "offline_access"
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
  realmSelector:
     matchLabels:
      realm: amq-sso-realm
